version: '3'

include:
  - proxy.yaml

services:
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports:
      - "3307:3306"
    networks:
      backend:
        ipv4_address: 172.20.0.10

  web:
  
    depends_on:
      - db

    build:
      context: .
      dockerfile: Dockerfile.python
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=db
    networks:
      backend:
        ipv4_address: 172.20.0.5